apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
      - name: backend
        image: quiz-backend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://quiz-mongo:27017/quizdb
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
spec:
  selector:
    app: quiz-backend
  ports:
  - port: 3000
    targetPort: 3000
